In [1]:
import numpy as np

# ── Creating arrays
a = np.array([1, 2, 3, 4, 5])                # 1D from list
b = np.array([[1, 2, 3], [4, 5, 6]])          # 2D matrix
c = np.zeros((3, 4))                          # 3×4 zeros
d = np.ones((2, 3))                           # 2×3 ones
e = np.eye(4)                                 # 4×4 identity
f = np.random.rand(3, 3)                      # Random [0,1)
g = np.arange(0, 20, 2)                       # [0, 2, 4,...18]
h = np.linspace(0, 1, 5)                      # [0, .25, .5, .75, 1]

print('1D array:', a)
print('2D array:\n', b)
print('Zeros:\n', c)
print('Identity:\n', e)
print('Range:', g)
print('Linspace:', h)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Range: [ 0  2  4  6  8 10 12 14 16 18]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [2]:
# ── Creating dictionaries
model_config = {
    'name'         : 'RandomForest',
    'n_estimators' : 100,
    'max_depth'    : 5,
    'random_state' : 42,
    'features'     : ['age', 'income', 'score']   # Value can be a list
}

# ── Accessing values
print(model_config['name'])                        # Direct access
print(model_config.get('n_estimators'))            # Safe access
print(model_config.get('learning_rate', 0.01))    # With default if missing

RandomForest
100
0.01


In [3]:
# ── Basic if / elif / else
accuracy = 0.87

if accuracy >= 0.95:
    status = '🏆 Excellent — Deploy to production'
elif accuracy >= 0.85:
    status = '✅ Good — Fine-tune and retest'
elif accuracy >= 0.70:
    status = '⚠️  Acceptable — Needs improvement'
else:
    status = '❌ Poor — Check data and features'

print(f'Accuracy {accuracy:.0%} → {status}')

# ── Comparison operators
x = 7
print(x == 7)    # Equal
print(x != 5)    # Not equal
print(x > 5)     # Greater than
print(x >= 7)    # Greater than or equal
print(x < 10)    # Less than

Accuracy 87% → ✅ Good — Fine-tune and retest
True
True
True
True
True


In [4]:
# ── for loop with range()
print('--- Training Progress ---')
for epoch in range(1, 6):          # 1 to 5
    loss = 1 / epoch               # Simulated decreasing loss
    print(f'Epoch {epoch}/5 | loss: {loss:.4f}')

--- Training Progress ---
Epoch 1/5 | loss: 1.0000
Epoch 2/5 | loss: 0.5000
Epoch 3/5 | loss: 0.3333
Epoch 4/5 | loss: 0.2500
Epoch 5/5 | loss: 0.2000


In [5]:
# ── Iterating over a list
feature_names = ['age', 'income', 'credit_score', 'num_accounts', 'debt_ratio']

for feature in feature_names:
    print(f'Processing feature: {feature}')

# ── enumerate() — get index AND value
print()
for idx, feature in enumerate(feature_names, start=1):
    print(f'{idx}. {feature}')

Processing feature: age
Processing feature: income
Processing feature: credit_score
Processing feature: num_accounts
Processing feature: debt_ratio

1. age
2. income
3. credit_score
4. num_accounts
5. debt_ratio


In [6]:
# ── while loop — use when you don't know how many iterations needed
import random
random.seed(42)

loss = 1.0
epoch = 0
target_loss = 0.35

print('Training until convergence...')
while loss > target_loss:
    loss -= random.uniform(0.05, 0.15)   # Simulate loss decrease
    loss  = max(loss, 0.0)               # Can't go below 0
    epoch += 1
    print(f'  Epoch {epoch:02d}: loss = {loss:.4f}')

print(f'\nConverged at epoch {epoch} with loss = {loss:.4f}')

Training until convergence...
  Epoch 01: loss = 0.8861
  Epoch 02: loss = 0.8336
  Epoch 03: loss = 0.7561
  Epoch 04: loss = 0.6837
  Epoch 05: loss = 0.5601
  Epoch 06: loss = 0.4424
  Epoch 07: loss = 0.3032

Converged at epoch 7 with loss = 0.3032


In [7]:
# ── break, continue, pass

# break — exit loop early
scores = [72, 85, 91, 63, 88, 95, 77]
for s in scores:
    if s >= 95:
        print(f'Found perfect score: {s} — stopping early')
        break
    print(f'Score: {s}')

# continue — skip current iteration
print('\nScores above 80 only:')
for s in scores:
    if s < 80:
        continue      # Skip low scores
    print(f'  {s}')

# Nested loops — hyperparameter search
print('\nGrid Search (simplified):')
for n_est in [50, 100, 200]:
    for depth in [3, 5, 7]:
        # In real code, you'd train here
        simulated_acc = round(0.80 + (n_est/1000) + (depth/100), 3)
        print(f'  n_estimators={n_est}, max_depth={depth} → acc={simulated_acc}')

Score: 72
Score: 85
Score: 91
Score: 63
Score: 88
Found perfect score: 95 — stopping early

Scores above 80 only:
  85
  91
  88
  95

Grid Search (simplified):
  n_estimators=50, max_depth=3 → acc=0.88
  n_estimators=50, max_depth=5 → acc=0.9
  n_estimators=50, max_depth=7 → acc=0.92
  n_estimators=100, max_depth=3 → acc=0.93
  n_estimators=100, max_depth=5 → acc=0.95
  n_estimators=100, max_depth=7 → acc=0.97
  n_estimators=200, max_depth=3 → acc=1.03
  n_estimators=200, max_depth=5 → acc=1.05
  n_estimators=200, max_depth=7 → acc=1.07
